### ISSUE TITLE
Example's Autocomplete extension

### ISSUE THREAD

**Issue by nicoip** [symfony2admingenerator/FormExtensionsBundle#44]
Hello,

Can you give me an example with Autocomplete extension ?

Thank you !

**Comment by ksn135** [comment]
https://github.com/symfony2admingenerator/FormExtensionsBundle/issues/14#issuecomment-66829101
https://gist.github.com/ksn135/447dfbf674f16b1e8e94

**Comment by nicoip** [comment]
Hi,

Thank @ksn135, but then I record a new employee directly too?

I wish to register new or existing tags

**Comment by ksn135** [comment]
I don't have an working example for now.
When and if you do it, then share the results with others.

**Comment by nicoip** [comment]
Ok,

You have  an idea to start ?

Yes ;)

**Comment by ksn135** [comment]
http://stackoverflow.com/questions/19903353/creating-new-tags-in-a-select2-tag-textarea <http://stackoverflow.com/questions/19903353/creating-new-tags-in-a-select2-tag-textarea>

**Comment by nicoip** [comment]
J'ai suivi ton lien.
Je récupère correctement la liste de tags, mais elle ne s'affiche pas...

```
<?php

namespace Ip\ItemBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * ActionsController
 */
class TagController  extends Controller
{


    public function ajaxAction(Request $request, $id = null)
    {
        try {
            $manager = $this->getDoctrine()->getManager();
                //->findByLibelle($request->request->get('q'));  
                            
            $results = $manager->getRepository("IpItemBundle:Tag")->createQueryBuilder('t')
               ->where('t.libelle like :libelle')
               ->setParameter('libelle', '%'.$request->request->get('q').'%')
               ->getQuery()
               ->getResult();                
                
            $serialized = $this->container->get('serializer')->serialize($results, 'json');
            return new JsonResponse([
                'success' => true,
                'results' => json_decode($serialized),
            ]);
        } catch (\Exception $exception) {
            return new JsonResponse([
                'success' => false,
                'code'    => $exception->getCode(),
                'message' => $exception->getMessage(),
            ]);
        }
    }                                         
    
    
}
```

```
      tags:
        filterable:  true
        label:       tags
        filterType:    s2a_select2_entity            
        formType:    s2a_select2_entity            
        addFormOptions:
            hidden:       true
            configs:
                placeholder: Please, choose a tag
                allowClear:  true
                minimumInputLength: 3
                ajax:
                    type: 'POST'
                    url: 'function() { return Routing.generate("ajax_get_tags", {_locale: "fr" }); }'
                    dataType: 'json'
                    quietMillis: 250
                    data: 'function (term, page) { return { q: term }; }'
                    results: 'function (data, page) { return { results: data.results }; }'
                    cache: true
                initSelection: 'function(element, callback) { var id = $(element).val(); if (id !== "") { $.ajax(Routing.generate("ajax_get_tag", {id: id}, _locale: "fr"), { type: "POST", dataType: "json" }).done(function(data) { callback(data.results[0]); });}}'
                    
                                    
```


```
      
ajax_get_tags:
    pattern: /ajax/get/tags
    defaults: 
        _controller: IpItemBundle:Tag:ajax 
    methods:  [POST]
    options:
        expose: true

ajax_get_tag:
    pattern: /ajax/get/tag/{id}
    defaults: 
        id: ~
        _controller: IpItemBundle:Tag:ajax
        _format: json
    methods:  [POST]
    options:
        expose: true      
      
      
```

**Comment by bobvandevijver** [comment]
@nicoip Please edit your last post so that your text is in English

**Comment by nicoip** [comment]
Sorry, done :)

**Comment by rpostolov** [comment]
Hi, i am using the same script has posted.

And i have the same problem, i retrieve the results but it don't appear.

Someone have an Idea ?

Thanks

**Comment by nicoip** [comment]
up :)

**Comment by bobvandevijver** [comment]
Let's have a look (I do not use this particular extension myself): Somewhere between the call for data and receiving the data something goes wrong. So some questions: 
- Is there any error in the console visible? 
- Can you trace the call in the JS and see what should happen?
- Have you checked that the returned data is in the correct format? Is it an JSON object and should it be an array, or the other way around?

By the way, why are you first serializing to `json_decode` it next?

I cannot debug any further now, but it would be awesome if you guys can do some digging in the JS by yourself :)

**Comment by nicoip** [comment]
Hello !
No, he has not error.

I do not know if the format is correct.

Do you have an example?

**Comment by bobvandevijver** [comment]
When I create an test from the code posted above, I get the following error (I've only adjusted the query and datatypes to match my application): 

```
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
``` 

This happens as the results do not have a `text` field. This can be solved by adding they next rule unded the `configs`:
```yaml
formatResults: function(){}
```

Now I already see empty rules appear in the widget: this means that we only need to add the correct formatter, in my case:
```yaml
formatResults: function(result){ return result.name; }
```
That's all it took :) My config generator.yml:
```yaml
    tags:
      filterable:  true
      label:       tags
      filterType:    s2a_select2_entity
      formType:    s2a_select2_entity
      addFormOptions:
        mapped: false
        hidden:       true
        class: Idb\IdbBundle\Entity\AppDeviceType
        configs:
          placeholder: Please, choose a tag
          allowClear:  true
          minimumInputLength: 3
          ajax:
            type: 'POST'
            url: 'function() { return Routing.generate("ajax_get_tags", {_locale: "en" }); }'
            dataType: 'json'
            quietMillis: 250
            data: 'function (term, page) { return { q: term }; }'
            results: 'function (data, page) { return { results: data.results }; }'
            cache: true
          initSelection: 'function(element, callback) { var id = $(element).val(); if (id !== "") { $.ajax(Routing.generate("ajax_get_tag", {id: id, _locale: "en"}), { type: "POST", dataType: "json" }).done(function(data) { callback(data.results[0]); });}}'
```

You can actually use different approaches and completely customize the rendering (see http://select2.github.io/select2/#documentation). 

You can also create this functionality in your model/controller: just make sure that you serialize the data with an text property.

Oh, and by the way: the current code @nicoip provided and is in my config does not handle errors from the 'API': a `success = 0` is still forwarded to the data parser of the select2 widget instead of notifying the user of an error.
