### ISSUE TITLE
Setup guide to update?

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/FormExtensionsBundle#51]
Env= SF2.7

1 problem when following the "setup guide":

```
An exception has been thrown during the rendering of a template ("There is no "formextensions_js" asset package.") in AdmingeneratorFormExtensionsBundle::javascripts.html.twig at line 79.
```

solve by adding:
```
framework:
    templating:
            formextensions_css:
                version: 1.0
                version_format: "%%1$s?v%%2$s"
            formextensions_js:
                version: 1.0
                version_format: "%%1$s?v%%2$s"
```

And for symfony2admingenerator/generatorbundle users, I think the javascript block to extend in base_admin.html.twig is ```{% block javascripts_head %}``` instead of ```{% block javascripts %}```
